#开发环境

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*xml
  type-aliases-package: com.lxxx.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

spring:
  #数据库连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/word_seg
    username: root
    password: 1234

knife4j:
  enable: true
  openapi:
    title: Knife4j官方文档
    description: "`我是测试`,**你知道吗**
    # aaa"
    email: xiaoymin@foxmail.com
    concat: 八一菜刀
    url: https://docs.xiaominfo.com
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: 分组名称
        api-rule: package
        api-rule-resources:
          - com.knife4j.demo.new3

seg:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: Lxxx
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token